apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: tenantc
spec:
  accessLogging:
    - disabled: false
      providers:
        - name: tenantc
  metrics:
    - overrides:
        - disabled: false
      providers:
        - name: prometheus
  tracing:
    - providers:
        - name: tenantc
      randomSamplingPercentage: 100
