pid_filename none

auth_param basic program /usr/lib64/squid/basic_ncsa_auth /etc/squid/htpasswd
auth_param basic children 5
auth_param basic realm Squid Secure Proxy
auth_param basic credentialsttl 2 hours
auth_param basic casesensitive off

acl authenticated proxy_auth REQUIRED

http_port 8080 ssl-bump cert=/certs/tls.crt key=/certs/tls.key generate-host-certificates=on dynamic_cert_mem_cache_size=4MB

https_port 8443 tls-cert=/certs/tls.crt tls-key=/certs/tls.key

acl step1 at_step SslBump1
ssl_bump peek step1
ssl_bump bump all

http_access allow authenticated
http_access deny all

sslcrtd_program /usr/lib64/squid/security_file_certgen -s /var/lib/squid/ssl_db -M 4MB
sslcrtd_children 5

cache_dir ufs /var/spool/squid 100 16 256
coredump_dir /var/spool/squid
access_log stdio:/proc/self/fd/1
cache_log stdio:/proc/self/fd/2
