apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: http
spec:
  exportTo:
  - '.'
  host: http
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 8443
        tls:
          mode: DISABLE
