apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-v3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: http
      version: v3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        inject.istio.io/templates: sidecar,spire
        sidecar.istio.io/nativeSidecar: 'true'
      creationTimestamp: null
      labels:
        app: http
        istio-locality: lab.hcp1-backup.zone5
        sidecar.istio.io/inject: 'true'
        spiffe.io/spire-managed-identity: 'true'
        version: v3
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin:latest
          imagePullPolicy: Always
          name: container
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: quayio
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
