apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quayio
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: registries/auth.json
        metadataPolicy: None
        property: data
      secretKey: datab64
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: quayio
    template:
      data:
        .dockerconfigjson: '{{ .datab64 }}'
      engineVersion: v2
      mergePolicy: Replace
      metadata: {}
      type: kubernetes.io/dockerconfigjson
