apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend1
  namespace: backends
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend2
  namespace: backends
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend3
  namespace: backends
---
