apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend1
  namespace: frontends
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend2
  namespace: frontends
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend3
  namespace: frontends
---
