apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    zonename: zone2
  name: http-zone2
spec:
  host: http.apps.example.com
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: gateway-v2
    weight: 100
  wildcardPolicy: None
