apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: http
  namespace: frontends
spec:
  exportTo:
    - .
    - gateways
  gateways:
    - gateways/gateway-v1
    - gateways/gateway-v2
  hosts:
    - http.apps.example.com
  http:
    - route:
        - destination:
            host: http.frontends.svc.cluster.local
            port:
              number: 8080
          weight: 100
