apiVersion: v1
kind: ServiceAccount
metadata:
  name: lbmonitor
  namespace: lbmonitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lbmonitor-role-frontends
  namespace: frontends
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lbmonitor-role-backends
  namespace: backends
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lbmonitor-rolebinding-frontends
  namespace: frontends
subjects:
- kind: ServiceAccount
  name: lbmonitor
  namespace: lbmonitor
roleRef:
  kind: Role
  name: lbmonitor-role-frontends
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lbmonitor-rolebinding-backends
  namespace: backends
subjects:
- kind: ServiceAccount
  name: lbmonitor
  namespace: lbmonitor
roleRef:
  kind: Role
  name: lbmonitor-role-backends
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lbmonitor-role-gateways
  namespace: gateways
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lbmonitor-rolebinding-gateways
  namespace: gateways
subjects:
- kind: ServiceAccount
  name: lbmonitor
  namespace: lbmonitor
roleRef:
  kind: Role
  name: lbmonitor-role-gateways
  apiGroup: rbac.authorization.k8s.io
---
