apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  labels:
    mode: sidecar
  name: metrics
  namespace: lbmonitor
spec:
  env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: MY_POD_LOCALITY
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['istio-locality']
  config:
    connectors:
      spanmetrics:
        metrics_flush_interval: 1s
        dimensions:
          - name: k8s.namespace.name
          - name: locality
        events:
          dimensions:
            - name: k8s.namespace.name
            - name: locality
          enabled: true
        exemplars:
          enabled: true
        namespace: span.metrics
    exporters:
      otlp_http/metrics:
        metrics_endpoint: http://metrics.monitoring.svc.cluster.local:9090/api/v1/otlp/v1/metrics
        tls:
          insecure: true
      otlp_http/logs:
        logs_endpoint: http://logs.monitoring.svc.cluster.local:3100/otlp/v1/logs
        tls:
          insecure: true
      otlp_http/traces:
        traces_endpoint: http://traces.monitoring.svc.cluster.local:4318/v1/traces
        tls:
          insecure: true
    processors:
      transform/add_pod_info:
        error_mode: ignore
        log_statements:
          - set(resource.attributes["k8s.pod.name"], "${env:MY_POD_NAME}")
          - set(resource.attributes["k8s.namespace.name"], "${env:MY_POD_NAMESPACE}")
          - set(resource.attributes["locality"], "${env:MY_POD_LOCALITY}")
        metric_statements:
          - set(resource.attributes["k8s.pod.name"], "${env:MY_POD_NAME}")
          - set(resource.attributes["k8s.namespace.name"], "${env:MY_POD_NAMESPACE}")
          - set(resource.attributes["locality"], "${env:MY_POD_LOCALITY}")
        trace_statements:
          - set(resource.attributes["k8s.pod.name"], "${env:MY_POD_NAME}")
          - set(resource.attributes["k8s.namespace.name"], "${env:MY_POD_NAMESPACE}")
          - set(resource.attributes["locality"], "${env:MY_POD_LOCALITY}")
      transform/enforce:
        error_mode: ignore
        log_statements:
          - merge_maps(log.attributes, resource.attributes, "upsert")
        metric_statements:
          - set(datapoint.attributes["namespace"], resource.attributes["k8s.namespace.name"]) where resource.attributes["k8s.namespace.name"] != nil
          - set(datapoint.attributes["locality"], resource.attributes["locality"]) where resource.attributes["locality"] != nil
          - merge_maps(datapoint.attributes, resource.attributes, "upsert")
        trace_statements:
          - merge_maps(span.attributes, resource.attributes, "upsert")
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      pipelines:
        logs:
          exporters:
            - otlp_http/logs
          processors:
            - transform/add_pod_info
            - transform/enforce
          receivers:
            - otlp
        metrics:
          exporters:
            - otlp_http/metrics
          processors:
            - transform/add_pod_info
            - transform/enforce
          receivers:
            - spanmetrics
            - otlp
        traces:
          exporters:
            - otlp_http/traces
            - spanmetrics
          processors:
            - transform/add_pod_info
            - transform/enforce
          receivers:
            - otlp
  mode: sidecar
  image: docker.io/otel/opentelemetry-collector-contrib:0.158.0
