apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: monitoring
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      appProtocol: http
  selector:
    app: metrics
  sessionAffinity: None
  trafficDistribution: PreferSameZone
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: logs
  namespace: monitoring
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 3100
      protocol: TCP
      targetPort: 3100
      appProtocol: http
  selector:
    app: logs
  sessionAffinity: None
  trafficDistribution: PreferSameZone
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: traces
  namespace: monitoring
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 4317
      protocol: TCP
      targetPort: 4317
      appProtocol: grpc
      name: grpc-http
    - port: 4318
      protocol: TCP
      targetPort: 4318
      appProtocol: http
      name: http-http
    - port: 3200
      protocol: TCP
      targetPort: 3200
      appProtocol: http
      name: http-query
  selector:
    app: traces
  sessionAffinity: None
  trafficDistribution: PreferSameZone
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      appProtocol: http
  selector:
    app: grafana
  sessionAffinity: None
  trafficDistribution: PreferSameZone
  type: LoadBalancer
---   
