apiVersion: opentelemetry.io/v1alpha1
kind: TargetAllocator
metadata:
  name: mesh
spec:
  observability:
    metrics:
      enableMetrics: true
  filterStrategy: relabel-config
  managementState: managed
  allocationStrategy: consistent-hashing
  serviceAccount: ta
  prometheusCR:
    enabled: true
    podMonitorSelector:
      matchExpressions:
        - key: tenant
          operator: In
          values:
            - tenantb
    scrapeInterval: 30s
    serviceMonitorSelector:
      matchExpressions:
        - key: tenant
          operator: In
          values:
            - tenantb
  replicas: 1
  collectorNotReadyGracePeriod: 30s
  ipFamilyPolicy: SingleStack
  podAnnotations:
    sidecar.istio.io/nativeSidecar: 'true'
