apiVersion: v1
data:
  client-id: VGVzdA==
  client-secret: Mzk3MjA1ODAtZmFkNC00NWIyLTljMmItY2M5ZWEyNTJkMzdj
  cookie-secret: empFeTZzeGpzc1pxRGY4RUVUVlpob1dNVkxQRS9Celo=
kind: Secret
metadata:
  creationTimestamp: null
  name: oauth2-proxy-creds
  namespace: istio-system
